import React, { useState, useEffect } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/cards'
import styles from '../styles/Home.module.css'
import MySocket from '../src/MySocket';

export default function Home() {
  const [players, setPlayers] = useState([])
  const socketInstance = MySocket.getInstance()
  const socket = socketInstance.socket;

  useEffect(() => {
    socket.emit('list-players', replay => {
      console.log('list-players', replay)
    })
  }, [])

  useEffect(() => {
    socket.on("packet", ({ type, data }) => {
      console.log('packet: ', type, data)
    });
  
    socket.on("listed-players", (data) => {
      console.log('listed-players: ', data)
      setPlayers(data)
    });

    socket.on("start-play", (data) => {
      console.log('start-play: ')
      router.push('/play')
    });

  }, [socket])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={[styles.main, "relative flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-rose-100 to-teal-100"]}>
        <div className="flex flex-col justify-center w-6/12 bg-white p-8">
          <div className="flex text-xl font-bold">Players:</div>
          <div className="flex flex-1 pl-8 mt-4">
            <ol className='text-lg'>
              { players.map((item, index) => {
                return <li key={index}>{item.name}</li>
              })}
            </ol>
          </div>
          <div className="flex flex-row space-x-4 my-4 h-80">
            <Card question={"Where is your favorite place on earh"} />
            <Card question={"What is your plan for next vacation"} />
            <Card question={"What it the most important thing in your life so far"}/>
          </div>
          <div className="flex flex-row space-x-4 my-4 justify-center">
            Click to Draw a Card
          </div>
          <div className="flex flex-row space-x-4 my-4">
            <button
              className="bg-red-400 text-white rounded-md hover:bg-red-500 font-semibold px-4 py-3"
            >
              Shuffle
            </button>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
